#!/bin/bash
echo "[tianrc  -  Haopeng Tian, May 2017]"
BASE_NAME=`basename \`pwd\``
EXPECTED_DIR_NAME=tianrc
echo -n "Checking conditions......"
if [ "$BASE_NAME" == "$EXPECTED_DIR_NAME" ]; then
    echo "Correct"
else
    echo "Incorrect. Please cd into tianrc directory"
    exit 0
fi

echo 
echo "------------------------------------------"
echo "Please backup your vimrc before proceeding"
echo "------------------------------------------"
echo "Install ? (y/n)"
read option
echo 

if [ "$option" != "y" ]; then
    exit
fi

echo "Installing config-lite-vim to ~"
echo 
echo "Step 1/3 - [Cloning Vundle...]"
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
echo 
echo "Step 2/3 - [Copying vimrc...]"
cp .vimrc ~/.vimrc
echo 
echo "Step 3/3 - [Install Plugin (Action Required)]"
echo 
echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
echo "Please start your vim ignoring all errors,"
echo "and type \":PluginInstall\" then press enter"
echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
echo 
